README.md

The listing in the Contributing section was done using inconsistent markdown syntax, which doesn't render well in some places like on the npm website (https://www.npmjs.com/package/elm-optimize-level-2#contributing)

Fix contribution listing in README

---

src/transforms/replaceListFunctions.ts

Hey Matt!
After receiving your message on Discourse I had another look at the `concat` implementation.
This PR fixes it.
I also wrote fuzz tests to test all the functions and nothing else showed up.
https://github.com/brian-carroll/list-map-modulo-cons/blob/master/src/HtmlTests.elm
Brian

Fix concat bug

---

notes/transformations.md
src/transform.ts
src/transforms/replaceStringFunctions.ts
src/types.ts

I've been experimenting with optimizations for the functions in Elm's String module, particularly on String.join and String.concat (which is implemented by a call to String.join) ([benchmark repository](https://gitlab.com/e-neighborhood-watch/elm-string-benchmarks/)). The optimized version of the String.join function in this PR is very similar to the improved join in the benchmark repository which shows [incredible improvements](https://e-neighborhood-watch.gitlab.io/elm-string-benchmarks/results/join/1.html) over the vanilla version of String.join.
I am not very familiar with typescript, so please let me know if it looks like there need to be fixed in any of my changes.

Replace String.join

---

src/transforms/replace.ts
src/transforms/utils/create.ts

This PR does two things:
1. replacements can now switch out a function declaration as opposed to just variables. (allows replacing kernel F2/A2 functions).
2. replacements can replace a variable/function with more than one statement. (allows to replace, say, the F function with a whole ton of stuff)

More flexible replacements

---

src/fs_util.ts
src/index.ts
src/replacements/faster-function-wrappers/A2.js
src/replacements/faster-function-wrappers/A3.js
src/replacements/faster-function-wrappers/A4.js
src/replacements/faster-function-wrappers/A5.js
src/replacements/faster-function-wrappers/A6.js
src/replacements/faster-function-wrappers/A7.js
src/replacements/faster-function-wrappers/A8.js
src/replacements/faster-function-wrappers/A9.js
src/replacements/faster-function-wrappers/F2.js
src/replacements/faster-function-wrappers/F3.js
src/replacements/faster-function-wrappers/F4.js
src/replacements/faster-function-wrappers/F5.js
src/replacements/faster-function-wrappers/F6.js
src/replacements/faster-function-wrappers/F7.js
src/replacements/faster-function-wrappers/F8.js
src/replacements/faster-function-wrappers/F9.js
src/types.ts
testcases/partial-application/Suite.elm
testcases/partial-application/V8/Benchmark.elm
testcases/partial-application/V8/Benchmark/Runner/Json.elm
testcases/partial-application/V8/Benchmark/Samples.elm
testcases/partial-application/V8/Benchmark/Status.elm
testcases/partial-application/V8/Debug.elm
testcases/partial-application/elm.json

`elm-optimize-level-2` currently re-writes code to perform direct function invocation when it knows it can be performed correctly. This increases performance in general, as most of the function calls in any given program is performed on a known function.
However, this optimization does very little (if anything at all) for functions that are passed as arguments to another function. In such cases we cannot know for certain what arity the function has, and so have no choice but to leave it alone.
In practice, that means that looping code like `List.foldl`, `List.map` and the like won't be as fast as they possibly could be.
This PR makes a small change to the existing function wrapper functions (`F2`, `F3`, `F4`, `A2`, `A3`, `A4`, etc.) in order to boost performance of making such calls.
The …

Optimized function wrappers

---

bin/elm-optimize-level-2.js
src/bin.ts
src/index.ts
src/run.ts

I added a way for Node.js project to import the project as a library and apply the optimizations, this will be useful for running these optimizations in `elm-review`.
You can review the changes commit by commit, but here are the highlights (not in the order of commits):
- Split `index.js` into
- `bin.js` which defines the `program` and handles the CLI part (and changed `bin/elm-optimize-level-2.js` to import this file).
- `index.js` which is the `main` file for the library part
- `run.js` which has the optimization-applyinh logic, and which is called from the previous 2 files.
- Added a lot more arguments to `run`, so that we can inject CLI or library-dependent behavior, and the wanted options from the CLI user or library user.
- Made `run` return the path to the output file
- Replaced …

Add Node.js library API

---

src/run.ts

I'm looking into ways to make `elm-optimize-level-2` faster and this looked like an easy win, though it will likely not change a lot. This will likely be how I run `elm-optimize-level-2` in `elm-review` (it is in a branch), and I imagine others will as well.

Prevent creating folder if input and output file paths are the same

---

notes/transformations.md

The proposed optimization seems to be already performed by the compiler.
I don't really know what to do: should we delete this part or keep it for documentation?
Sidenote: in elm, we don't have any "statement", only "expressions" and "definitions".

Add note about "Skip Allocating Tuples in Case"

---

src/run.ts

I previously added processOpts as an argument, but forgot to use. The value used in the CLI and the default value for the Node.js lib are the same as the one removed here.

Use processOpts from options

---

src/replacements/list/$elm$core$List$concat.js

I stumbled upon this replacement file, and noticed some variables where always defined but only used in one of the branches.
Here is a benchmark comparing the 2: https://jsbench.me/fpkuwkrzz9/1
The result is that for empty lists the newer version is faster.
I also tried it for non-empty list, and benchmarks seems to indicate one is faster than the other about half of the time, which I imagine means they're roughly equivalent. https://jsbench.me/jwkuwl92mi/1

Remove unnecessary work from $elm$core$List$concat replacement

---

src/transforms/replace.ts

This makes it so that the `replace` transformer stops recursing through the AST as soon as it finds the level where it finds some statements.
I ran level-2 5 times on each version. Times are in milliseconds (and ordered from lower to higher)
| Version | Attempt 1 | 2 | 3 | 4 | 5 |
|--|--|--|--|--|--|
| Before | 1595 | 1658 | 1691 | 1709 | 1769 | 1684 |
| After | 1534 | 1541 | 1546 | 1566 | 1580 | 1553 |
This averages on a ~8% speedup on the entire run of the program.
I compared the output of level-2 before and after this change and they are identical.
I haven't looked at other transformations, but maybe the same optimization can be applied in other places as well.

replace transforms: Don't go through all nodes

---

src/transforms/passUnwrappedFunctions.ts

This only renames an argument with a typo.

Fix typo in source code

---

src/replacements/list/$elm$core$List$all.js

This makes `List.all` quite a lot faster. The problem is the original uses this implementation:
```elm
var $elm$core$List$all = F2(
function (isOkay, list) {
return !A2(
$elm$core$List$any,
A2($elm$core$Basics$composeL, $elm$core$Basics$not, isOkay),
list);
});
```
The `composeL` (or `<<` in Elm) is actually not very performant ([benchmark](https://github.com/jfmengels/elm-benchmarks/blob/master/src/WhatIsFaster/FunctionComposition.elm), [results](https://github.com/jfmengels/elm-benchmarks/blob/master/src/WhatIsFaster/FunctionComposition-Results-Chrome.png)). We could also make the same change by transforming `composeL`/`composeR` calls by anonymous functions, but that's more work. I do plan to add that, at which point we can probably remove this replacement (EDIT: done in #73).
I …

Add replacement for List.all

---

src/fs_util.ts
src/transform.ts
src/transforms/replace.ts
src/types.ts

This merges all replace transforms into one, meaning that we will only have to do a single AST pass for all these replacements.
- Use promises to find and load the replacement files in parallel
- Avoid loading replacement files that will not be enabled
- Merge all replacements together
- Use `fs.readdir(dir, {withFileTypes: true})` to avoid having to do `fs.stat` (I didn't know about this before. I haven't benchmarked whether it's better tbh)
- Remove some unused imports
I did a very quick benchmark and I see a 5% speed improvement on the total run, but I'm not entirely sure my benchmark was run sufficiently to be conclusive. Anyway, the more replacement transforms that get added, the more this will be worth it, so I think it's a good foundation.
Let me know if there is a part of this you …

Single replace pass

---

src/replacements/string/$elm$core$String$repeat.js

This is a replacement for `String.repeat`
```elm
repeat : Int -> String -> String
repeat n chunk =
repeatHelp n chunk ""
repeatHelp : Int -> String -> String -> String
repeatHelp n chunk result =
if n <= 0 then
result
else
repeatHelp (Bitwise.shiftRightBy 1 n) (chunk ++ chunk) <|
if Bitwise.and n 1 == 0 then
result
else
result ++ chunk
```
The replacement is equivalent to the following Elm code:
```elm
repeat : Int -> String -> String
repeat n chunk =
repeatHelp n chunk ""
repeatHelp : Int -> String -> String -> String
repeatHelp n chunk result =
if n <= 0 then
result
else
repeatHelp (Bitwise.shiftRightBy 1 n)
(chunk ++ chunk ++ "")
(if Bitwise.and n 1 == 0 then
result
else
result ++ chunk ++ ""
)
```
The main improvements are:
- the function is made tailcall recursive (by removing the …

Add replacement for String.repeat

---

src/replacements/list/$elm$core$List$take.js

This is applying the same technique from other List optimizations and applying it to `List.take`.
Benchmark can be found [here](https://github.com/jfmengels/elm-benchmarks/blob/master/src/ImprovingPerformance/ElmCore/ListTake.elm).
Here are the improvements for Chrome:
and for Firefox:
The results are very much alike when compiling with or without `elm-optimize-level-2`.

Add replacement for List.take

---

src/replacements/list/$elm$core$List$concatMap.js

I'm back! My Elm solution from #66 was beat by the improvements `elm-optimize-level-2` already did by replacing `List.concat`. By applying the same technique on `concatMap`, we can make it faster than before.
This removes the need to iterate through the list twice (once for map, then once for concat).
(cc @brian-carroll who seems to have made the original series of these improvements on Lists)
Here are the [benchmarks](https://github.com/jfmengels/elm-benchmarks/blob/master/src/ImprovingPerformance/ElmCore/ListConcatMap.elm) results for Chrome:
and for FIrefox:

Add List concatMap replacement

---

src/replacements/list/_List_map2.js
src/replacements/list/_List_map3.js
src/replacements/list/_List_map4.js
src/replacements/list/_List_map5.js

This improves the performance for all `List.map2`, `List.map3`, `List.map4` and `List.map5`, using the same idea as for other List replacements.
I have only [benchmarked it for `List.map2`](https://github.com/jfmengels/elm-benchmarks/blob/master/src/ImprovingPerformance/ElmCore/ListMap2.elm), which gives the following results (against eol2):
Chrome:
FF:

Add replacements for List.mapN functions

---

CHANGELOG.md
package.json
src/transform.ts

- Fix "phantom comments" from JS source from intermingling w/ record-optimization output.
- Bump TS
Depends on https://github.com/mdgriffith/elm-optimize-level-2/pull/83 because of the addition of a changelog. Would point at the PR if I could.

Fix phantom comments causing runtime exceptions

---

src/transforms/inlineWrappedFunctions.ts
src/transforms/patterns.ts
src/transforms/utils/ElmWrappers.ts
src/transforms/utils/callgraph.ts

Fixes the issue reported in https://github.com/mdgriffith/elm-optimize-level-2/pull/90
The code was looking for `A2` wrappers and the likes, and extracting the arity out of that (2 for `A2`, 3 for `A3`...).
The root issue was that the regex used to match and extract that arity was too permissive, making functions like `$folkertdev$elm_sha2$Internal$SHA256$loopHelp` be considered as an Elm wrapper function with 256 arguments (`A256`...).
This happened in the `patterns` module used by the `passUnwrappedFunctions` transformer.
I fixed the issue by changing `/A.../;` to `/^A.../;` I also added a `$` at the end just to be safe.
Since this regex was re-declared in multiple modules (and even correct in one of them :man_facepalming: ), I mutualized them into a single helper module, and decided to …

Correct AX and FX regex
